---
# tasks file for roles/osp-instance-delete
- name: Fetch Instance Info
  os_server_info:
    cloud: "{{ openstack_cloud | default('openstack') }}"
  register: r_os_servers

- name: Delete instances
  os_server:
    cloud: "{{ openstack_cloud | default('openstack') }}"
    name: "{{ item.name }}"
    state: absent
    delete_fip: true
  loop: "{{ r_os_servers.openstack_servers }}"
