# Fetch GUIDkey.pem from bastion of Three tier application env and create machine credential to connect to AWS instances

- hosts: tag_AnsibleGroup_bastions
  gather_facts: true
  become: true
  vars_files:
    - vars/secrets.yml
  roles:
  - aws-creds
