# Smoke test for QA 3 tier app in OSP environment
# To be executed from Tower isolated node (workstation)

- hosts: localhost
  gather_facts: false
  tasks:

  - name: OpenStack servers
    os_server_info:
      cloud: "{{ openstack_cloud | default('openstack') }}"
      filters:
        metadata.group: frontends
    register: r_os_servers

  - name: Curl website
    uri:
      url: "http://{{ item.public_v4 }}"
      return_content: yes
      status_code: 200
    loop: "{{ r_os_servers.openstack_servers }}"

  - name: Fail if 'Ansible has done its job' is not in the page content
    fail:
    when: "'Ansible has done its job' not in webpage.results[0].content"
    tags:
      - osp.smoke
