---
# Provision AWS lab

- name: create bin directory
  file:
    path: ~/bin
    state: directory
- name: get script common.sh
  get_url:
    url: "{{ param_repo_base }}/scripts/common.sh"
    dest: ~/common.sh
    mode: 0755

- name: get script jq
  get_url:
    url: "{{ param_repo_base }}/scripts/jq-linux64"
    dest: ~/bin/jq
    mode: 0755
- name: get script order_svc.sh
  get_url:
    url: "{{ param_repo_base }}/scripts/order_svc.sh"
    dest: ~/order_svc.sh
    mode: 0755
- name: create credentials
  copy:
    content: |
      export username='{{ param_user }}'
      export password='{{ param_password }}'
      export uri=https://labs.opentlc.com
    dest: ~/credential.rc
    mode: 0755

# Fix the existing shell scripts to reference jq command with bin/jq
- name: fix scripts
  #shell: "sed -i 's/ jq/ bin\\/jq/g' {{ item }}"
  replace:
    path: "{{ item }}"
    regexp: ' jq'
    replace: ' ~/bin/jq'
  with_items:
    - ~/common.sh
    - ~/order_svc.sh

# Using this script will always deploy environments in the us-east-1 region.
- name: order service on opentlc
  shell: source ~/credential.rc; ~/order_svc.sh -y -c 'OPENTLC Automation' -i 'Ansible Advanced - Three Tier App' -t 1 -d 'dialog_expiration=7;region=na;nodes=1;dialog_runtime=8;notes=Training - As part of course'
  args:
    chdir: ~
- name: Wait for mail
  pause:
    minutes: 10
