---
# Build in-memory OSP inventory

- name: Fetch Instance Info
  os_server_info:
    cloud: openstack
  register: result

- name: inspect os_server_info
  debug:
    var: item
  with_items: "{{result.openstack_servers}}"

- name: Add host
  add_host:
    name: "{{ item.public_v4 }}"
    group: "{{ item.metadata.group }}"
    ansible_ssh_private_key_file: "/root/.ssh/openstack.pem"
    ansible_ssh_user: cloud-user
  with_items: "{{result.openstack_servers}}"

- name: Add host
  add_host:
    name: "{{ item.public_v4 }}"
    group: "{{ item.metadata.deployment_name }}"
    ansible_ssh_private_key_file: "/root/.ssh/openstack.pem"
    ansible_ssh_user: cloud-user
  with_items: "{{result.openstack_servers}}"
