# Create Tower job templates

- name: Job template for OSP Instances
  tower_job_template:
    name: "{{job_template_name_osp_instances}}"
    job_type: "run"
    inventory: "{{static_inventory_name}}"
    project: "{{proj_name}}"
    playbook: "{{osp_instances_playbook}}"
    credential: "{{ssh_cred_name}}"
    state: "present"

- name: Associate IG to OSP instances job template 
  command: |
    tower-cli job_template associate_ig --job-template "{{job_template_name_osp_instances}}" --instance-group "{{instance_group_name}}"


- name: Create vault credential
  tower_credential:
    name: "vault-cred"
    organization: "{{org_name}}"
    state: present
    kind: vault
    vault_password: "ansible"

- name: Job template for 3tier app deploy on QA Env
  tower_job_template:
    name: "{{job_template_name_3tier_app}}"
    job_type: "run"
    inventory: "{{static_inventory_name}}"
    project: "{{proj_name}}"
    playbook: "{{app_deploy_playbook}}"
    credential: "{{ssh_cred_name}}"
    state: "present"

- name: Associate IG to 3tier job template  
  command: |
    tower-cli job_template associate_ig --job-template "{{job_template_name_3tier_app}}" --instance-group "{{instance_group_name}}"


- name: Job template to delete OSP Instances
  tower_job_template:
    name: "{{job_template_name_osp_instances_delete}}"
    job_type: "run"
    inventory: "{{static_inventory_name}}"
    project: "{{proj_name}}"
    playbook: "{{osp_instances_delete_playbook}}"
    credential: "{{ssh_cred_name}}"
    state: "present"

- name: Associate IG to OSP Delete instances job template 
  command: |
    tower-cli job_template associate_ig --job-template "{{job_template_name_osp_instances_delete}}" --instance-group "{{instance_group_name}}"


- name: Job template for smoke test osp instances
  tower_job_template:
    name: "{{job_template_smoke_osp}}"
    job_type: "run"
    inventory: "{{static_inventory_name}}"
    project: "{{proj_name}}"
    playbook: "{{osp_smoke_playbook}}"
    credential: "{{ssh_cred_name}}"
    state: "present"

- name: Associate IG to Smoke test job template 
  command: |
    tower-cli job_template associate_ig --job-template "{{job_template_smoke_osp}}" --instance-group "{{instance_group_name}}"

- name: Job template for Provisioning AWS env
  tower_job_template:
    name: "{{job_template_aws_provision}}"
    job_type: "run"
    inventory: "{{static_inventory_name}}"
    project: "{{proj_name}}"
    playbook: "{{aws_provision_playbook}}"
    credential: "{{ssh_cred_name}}"
    extra_vars_path: /tmp/aws_jq_vars.yml
    state: "present"

- name: Job template for injecting AWS SSH keys
  tower_job_template:
    name: "{{job_template_aws_ssh_keys}}"
    job_type: "run"
    inventory: "{{ec2_dynamic_inventory}}"
    project: "{{proj_name}}"
    playbook: "{{aws_ssh_playbook}}"
    credential: "{{opentlc_cred_name}}"
    extra_vars_path: "/tmp/tower_info.yml"
    state: "present"

- name: Associate vault credential with AWS SSH keys job template
  command: |
    tower-cli job_template associate_credential --job-template "{{job_template_aws_ssh_keys}}" --credential "vault-cred"

- name: Job template for checking AWS instances status
  tower_job_template:
    name: "{{job_template_aws_status_check}}"
    job_type: "run"
    inventory: "{{ec2_dynamic_inventory}}"
    project: "{{proj_name}}"
    playbook: "{{aws_status_playbook}}"
    credential: "{{opentlc_cred_name}}"
    state: "present"

- name: Job template for 3tier AWS deploy
  tower_job_template:
    name: "{{job_template_name_3tier_app_aws}}"
    job_type: "run"
    inventory: "{{ec2_dynamic_inventory}}"
    project: "{{proj_name}}"
    playbook: "{{app_deploy_playbook}}"
    credential: "vault-cred"
    state: "present"

- name: Job template for smoke test aws instances
  tower_job_template:
    name: "{{job_template_smoke_aws}}"
    job_type: "run"
    inventory: "{{ec2_dynamic_inventory}}"
    project: "{{proj_name}}"
    playbook: "{{aws_smoke_app_playbook}}"
    credential: "vault-cred"
    state: "present"
