- name: Verify that we have all required variables
  fail: msg="The 'tower_GUID' variable is not defined or empty"
  when: (tower_GUID is not defined) or (tower_GUID|length == 0)

- name: Create Homework Assignment project
  tower_project:
    name: "{{proj_name}}"
    description: "Homework Assignment project"
    organization: "{{org_name}}"
    scm_type: git
    scm_url: "{{github_repo}}"
    scm_branch: "homework"
# TODO: change branch name
    scm_update_on_launch: True
    state: present

- name: Machine Credentail to connect to workstation using openstack.pub
  tower_credential:
    name: Connect_to_workstation
    organization: Default
    state: present
    kind: ssh
    tower_host: tower1.{{tower_GUID}}.example.opentlc.com
    tower_username: admin
    tower_password: r3dh4t1!
    ssh_key_data: "{{ lookup('file', '/root/.ssh/openstack.pem') }}"
    username: cloud-user

- name: Create Inventory
  tower_inventory:
    name: "{{static_inventory_name}}"
    organization: "{{org_name}}"
    state: present


- name: Add tower host
  tower_host:
    name: "{{host_name}}"
    description: "workstation"
    inventory: "{{static_inventory_name}}"
    state: present
    tower_host: tower1.{{tower_GUID}}.example.opentlc.com
    tower_username: admin
    tower_password: r3dh4t1!
    tower_verify_ssl: no


- name: Create Group in static inventory 
  tower_group:
    name: "{{group_name}}"
    inventory: "{{static_inventory_name}}"
    state: present
    instance_filters: "{{host_name}}"


#- name: Associate workstation host to group 
#  command: | 
#    tower-cli host associate --host "{{host_name}}" --group "{{group_name}}"


- name: Tower Creds key file
  tower_credential:
    name: "{{ opentlc_cred_name }}"
    organization: Default
    state: present
    kind: ssh
    tower_host: tower1.{{tower_GUID}}.example.opentlc.com
    tower_username: admin
    tower_password: r3dh4t1!
    tower_verify_ssl: no
    ssh_key_data: "{{ lookup('file', '/root/.ssh/mykey.pem') }}"
    username: "{{ opentlc_login }}"

- name: Remove secret
  file:
    name: /root/secret.pem
    state: absent
