# Create Tower workflow from `workflow.j2` template
- name: Create workflow schema 
  template:
    src: workflow.j2
    dest: /root/workflow.yml

- name: Create CI CD Workflow
  command: |
    tower-cli workflow create -n {{workflow_template_name}} --organization {{org_name}}
  tower_workflow_template:
    name: "{{workflow_template_name}}"
    organization: "{{org_name}}"
    schema: "{{ lookup('file', '/root/workflow.yml') }}"
